import type { Email, Trip, Task, Brief } from "./types";

export const mockEmails: Email[] = [
  {
    id: "1",
    from: "James Okafor",
    fromRole: "CEO",
    subject: "Q3 Board Deck – Final Review Needed",
    summary: "Board presentation requires your sign-off before Thursday's send. Slides 12–18 need updated financials.",
    body: "Hi,\n\nPlease review the attached Q3 board deck. We need final sign-off before we send to the board by Thursday 5pm. In particular, slides 12–18 require the updated financial figures from CFO.\n\nBest,\nJames",
    action: "Reply",
    priority: "high",
    isVIP: true,
    timestamp: "2026-05-02T08:15:00Z",
    read: false,
    tags: ["Board", "Q3"],
  },
  {
    id: "2",
    from: "Amara Singh",
    fromRole: "CFO",
    subject: "Budget Variance Report – April",
    summary: "April opex ran 8% over budget. CFO wants a call to discuss mitigation strategy.",
    body: "Following up on the April close. Opex came in at 8% over budget primarily driven by the accelerated hiring in the product org. I'd like to schedule a 30-min call with you and the CEO to discuss mitigation options before the board meeting.\n\nAre you available Thursday at 2pm?\n\nAmara",
    action: "Reply",
    priority: "high",
    isVIP: true,
    timestamp: "2026-05-02T07:45:00Z",
    read: false,
    tags: ["Finance", "Budget"],
  },
  {
    id: "3",
    from: "Lena Torres",
    fromRole: "CTO",
    subject: "Platform Migration Update",
    summary: "Migration to new infrastructure on track. Minor delay in EU region – resolved by EOW.",
    body: "Quick update on the platform migration. We're on track for the May 15 cutover. The EU region had a minor configuration issue that pushed us back 2 days, but that is now resolved and we'll be back on schedule by end of week.\n\nNo action needed from your side.\n\nLena",
    action: "No Action",
    priority: "medium",
    isVIP: true,
    timestamp: "2026-05-01T17:30:00Z",
    read: true,
    tags: ["Tech", "Migration"],
  },
  {
    id: "4",
    from: "Marcus Webb",
    fromRole: "Head of Strategy",
    subject: "Competitive Intelligence – New Entrant",
    summary: "New competitor raised $40M Series B. Recommend briefing CEO before weekly leadership meeting.",
    body: "FYI – I've been tracking a new entrant in our core market. They just announced a $40M Series B this morning. I've drafted a 2-page brief. Recommend we find 10 minutes to brief the CEO before Monday's leadership meeting.\n\nI'll send the brief separately.\n\nMarcus",
    action: "Delegate",
    priority: "high",
    isVIP: false,
    timestamp: "2026-05-01T14:20:00Z",
    read: false,
    tags: ["Strategy", "Competitive"],
  },
  {
    id: "5",
    from: "Priya Nair",
    fromRole: "EA to CEO",
    subject: "CEO Calendar – Week of May 6",
    summary: "CEO's week fully blocked. Two external meetings require your briefing packs by Friday.",
    body: "Hi,\n\nSharing the CEO's schedule for week of May 6 for your awareness. Two external meetings require briefing packs:\n\n1. Tuesday 10am – Partnership meeting with Helios Capital (30 mins)\n2. Thursday 3pm – Government affairs meeting (45 mins)\n\nBriefing packs needed by Friday EOD please.\n\nThanks,\nPriya",
    action: "Reply",
    priority: "medium",
    isVIP: false,
    timestamp: "2026-05-01T11:00:00Z",
    read: false,
    tags: ["Calendar", "Briefings"],
  },
  {
    id: "6",
    from: "David Chen",
    fromRole: "Product Leader",
    subject: "Q2 Product Roadmap – Stakeholder Sign-off",
    summary: "Product roadmap ready for CEO sign-off. Key decision: prioritize AI features vs. platform stability.",
    body: "The Q2 roadmap is finalized pending CEO sign-off. The key open decision is whether we prioritize the AI feature suite (higher revenue potential, higher risk) vs. platform stability work (lower revenue impact, reduces tech debt).\n\nI'd like 20 mins on the CEO's calendar to walk through the trade-offs.\n\nDavid",
    action: "Delegate",
    priority: "medium",
    isVIP: false,
    timestamp: "2026-04-30T16:45:00Z",
    read: true,
    tags: ["Product", "Roadmap"],
  },
];

export const mockTrips: Trip[] = [
  {
    id: "1",
    title: "NYC Leadership Summit",
    from: "London",
    fromAirport: "Heathrow (LHR)",
    to: "New York",
    toAirport: "JFK International (JFK)",
    departureTime: "2026-05-10T09:00:00Z",
    arrivalTime: "2026-05-10T14:30:00Z",
    airline: "British Airways",
    flightNumber: "BA177",
    brief: "CEO attending 2-day Leadership Summit at the Plaza Hotel. Key meetings include Helios Capital partnership discussion (Day 1), panel appearance on AI in Finance (Day 2), and bilateral with Meridian Group CEO.",
    ceoNotes: "CEO prefers aisle seat. Car service pre-booked from JFK. Hotel check-in at 3pm. Dinner with the Meridian team at 7pm – business casual.",
    reminders: [
      "Online check-in opens 24hrs before departure (May 9, 9am)",
      "Prepare briefing pack for Helios Capital meeting",
      "Confirm car service pickup time from JFK",
      "Pack agenda and business cards",
    ],
    createdAt: "2026-05-01T10:00:00Z",
  },
];

export const mockTasks: Task[] = [
  {
    id: "1",
    title: "Prepare Q3 Board Deck Review",
    description: "Review slides 12-18 with updated financials from CFO before Thursday 5pm",
    status: "inprogress",
    priority: "high",
    assignee: "Chief of Staff",
    linkedEmailId: "1",
    dueDate: "2026-05-05",
    createdAt: "2026-05-02T08:30:00Z",
  },
  {
    id: "2",
    title: "Schedule CFO Call re Budget Variance",
    description: "Coordinate Thursday 2pm call between CEO and CFO to discuss April budget overrun mitigation",
    status: "todo",
    priority: "high",
    assignee: "Chief of Staff",
    linkedEmailId: "2",
    dueDate: "2026-05-03",
    createdAt: "2026-05-02T08:00:00Z",
  },
  {
    id: "3",
    title: "Brief CEO on New Competitor",
    description: "Summarize Marcus Webb's competitive intel brief on new $40M entrant. Book 10 min before leadership meeting",
    status: "todo",
    priority: "high",
    assignee: "Chief of Staff",
    linkedEmailId: "4",
    dueDate: "2026-05-04",
    createdAt: "2026-05-01T14:30:00Z",
  },
  {
    id: "4",
    title: "Prepare Helios Capital Briefing Pack",
    description: "Brief on Helios Capital – fund size, key partners, strategic rationale for partnership",
    status: "waiting",
    priority: "medium",
    assignee: "Marcus Webb",
    dueDate: "2026-05-05",
    createdAt: "2026-05-01T12:00:00Z",
  },
  {
    id: "5",
    title: "Coordinate CEO Product Roadmap Session",
    description: "Book 20 min with CEO and David Chen to walk through Q2 roadmap AI vs. stability trade-offs",
    status: "todo",
    priority: "medium",
    assignee: "Chief of Staff",
    linkedEmailId: "6",
    dueDate: "2026-05-06",
    createdAt: "2026-04-30T17:00:00Z",
  },
  {
    id: "6",
    title: "NYC Trip Logistics Confirmed",
    description: "Car service, hotel, and summit registration all confirmed for May 10",
    status: "done",
    priority: "medium",
    assignee: "Chief of Staff",
    dueDate: "2026-05-03",
    createdAt: "2026-04-28T09:00:00Z",
  },
];

export const mockBrief: Brief = {
  id: "1",
  title: "Weekly Executive Brief – May 2, 2026",
  rawInput: "",
  keyUpdates: [
    "Q3 Board Deck requires CEO sign-off by Thursday 5pm; slides 12–18 need updated financials from CFO",
    "April opex ran 8% over budget driven by accelerated product hiring; CFO requesting CEO call",
    "Platform migration on track for May 15 cutover; EU region delay resolved",
    "New competitor raised $40M Series B this morning – competitive brief being prepared",
  ],
  decisionsRequired: [
    "Q2 Product Roadmap: AI feature suite vs. platform stability prioritisation",
    "Budget mitigation strategy for April opex overrun (8% above target)",
  ],
  risks: [
    "Board deck sign-off at risk if CFO financials not delivered by Wednesday EOD",
    "Competitive landscape shift: new well-funded entrant in core market requires rapid strategic response",
  ],
  nextSteps: [
    "CoS: Send Q3 board deck to CEO for review today",
    "CoS: Confirm Thursday 2pm call between CEO and CFO",
    "Marcus Webb: Deliver competitive intelligence brief by Friday",
    "CoS: Book CEO + Product 20-min roadmap session before May 9",
    "CoS: Prepare Helios Capital briefing pack by May 5",
  ],
  createdAt: "2026-05-02T09:00:00Z",
};
